import {
  User,
  StudentRecord,
  Application,
  Document,
  Notification,
  Program,
  StageHistory,
} from "./types";

export const mockUser: User = {
  id: "user-123",
  email: "john.doe@bennett.edu.in",
  display_name: "John Doe",
  role: "student",
  photo_uri: null, // use placeholder
  mobile: "+91 9876543210",
};

export const mockStudentRecord: StudentRecord = {
  id: "sr-123",
  user_id: "user-123",
  enrollment_id: "E20CS123",
  department: "B.Tech CSE",
  batch_year: 2024,
  program_type: "Undergraduate",
};

export const mockProgram: Program = {
  id: "prog-1",
  title: "Singapore Summer School 2025 \u2014 Singapore Management University",
  country: "Singapore",
  duration: "4 Weeks",
  fee: 40000,
  poc: {
    name: "Dr. Jane Smith",
    designation: "Program Coordinator",
    email: "janesmith@smu.edu.sg",
    contactNumber: "+65 6828 0100",
  },
};

export const mockApplication: Application = {
  id: "app-123",
  user_id: "user-123",
  program_id: "prog-1",
  stage: "offer_letter",
  fee_paid: true,
  departure_date: "2025-07-15",
  applied_at: "2025-05-12T15:18:00Z",
};

export const mockApplicationsList = [
  {
    id: "app-123",
    program_title: "Singapore Summer School 2025 — Singapore Management University",
    status: "In Process",
    applied_at: "2025-05-12T15:18:00Z",
  },
  {
    id: "app-124",
    program_title: "HSE St. Petersburg Summer School",
    status: "Accepted",
    applied_at: "2024-11-20T10:00:00Z",
  },
  {
    id: "app-125",
    program_title: "Semester Exchange at University of Queensland",
    status: "Completed",
    applied_at: "2023-08-10T14:30:00Z",
  }
];


export const mockDocuments: Document[] = [
  {
    id: "doc-1",
    user_id: "user-123",
    application_id: "app-123",
    type: "passport",
    status: "verified",
    r2_key: "passport.pdf",
    verified_at: "2025-05-18T11:20:00Z",
  },
  {
    id: "doc-2",
    user_id: "user-123",
    application_id: "app-123",
    type: "transcript",
    status: "verified",
    r2_key: "transcripts.pdf",
    verified_at: "2025-05-18T11:20:00Z",
  },
  {
    id: "doc-3",
    user_id: "user-123",
    application_id: "app-123",
    type: "photo",
    status: "verified",
    r2_key: "photo.jpg",
    verified_at: "2025-05-18T11:20:00Z",
  },
  {
    id: "doc-4",
    user_id: "user-123",
    application_id: "app-123",
    type: "sop",
    status: "pending",
    r2_key: "sop.pdf",
    verified_at: null,
  },
  {
    id: "doc-5",
    user_id: "user-123",
    application_id: "app-123",
    type: "bank_statement",
    status: "pending",
    r2_key: "bank_statement.pdf",
    verified_at: null,
  },
  {
    id: "doc-6",
    user_id: "user-123",
    application_id: "app-123",
    type: "vaccination",
    status: "pending",
    r2_key: "vax.pdf",
    verified_at: null,
  },
  {
    id: "doc-7",
    user_id: "user-123",
    application_id: "app-123",
    type: "aadhaar",
    status: "not_uploaded",
    r2_key: null,
    verified_at: null,
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "notif-1",
    subject: "Offer Letter Ready \u2014 Download Now",
    body_html: "Your offer letter for Singapore Summer School 2025 has been generated...",
    sent_at: "2025-05-24T14:41:00Z",
    read: false,
  },
  {
    id: "notif-2",
    subject: "Documents Approved",
    body_html: "3 of your submitted documents have been verified by the OIA team...",
    sent_at: "2025-05-18T11:20:00Z",
    read: false,
  },
  {
    id: "notif-3",
    subject: "Application Received",
    body_html: "We have received your application for Singapore Summer School 2025...",
    sent_at: "2025-05-12T15:18:00Z",
    read: true,
  },
];

export const mockStageHistory: StageHistory[] = [
  {
    id: "sh-1",
    application_id: "app-123",
    from_stage: null,
    to_stage: "applied",
    note: "Application submitted successfully",
    changed_at: "2025-05-12T15:18:00Z",
  },
  {
    id: "sh-2",
    application_id: "app-123",
    from_stage: "applied",
    to_stage: "documents_verified",
    note: "Documents verified by OIA team \u2014 3 items approved",
    changed_at: "2025-05-18T11:20:00Z",
  },
  {
    id: "sh-3",
    application_id: "app-123",
    from_stage: "documents_verified",
    to_stage: "offer_letter",
    note: "Offer letter generated by OIA team",
    changed_at: "2025-05-24T14:41:00Z",
  },
];

export const mockApplicationComments: import("./types").ApplicationComment[] = [
  {
    id: "comment-1",
    application_id: "app-123",
    sender: "admin",
    text: "Please upload your updated passport copy. The current one expires soon.",
    created_at: "2025-05-13T10:00:00Z",
  },
  {
    id: "comment-2",
    application_id: "app-123",
    sender: "student",
    text: "Attached my updated passport copy here.",
    media_url: "passport_updated_2025.pdf",
    created_at: "2025-05-14T11:20:00Z",
  },
  {
    id: "comment-3",
    application_id: "app-123",
    sender: "admin",
    text: "Thanks! We've verified it.",
    created_at: "2025-05-14T12:00:00Z",
  }
];
